 development:
   push_notify_incomplete_task:
     class: PushLineJob
     queue: background
     schedule: at 9am every day
   periodic_command:
     command: "SoftDeletedRecord.due.delete_all"
     priority: 2
     schedule: at 5am every day
